name = "ishyura"
main = "dist/server/server.js"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist/client"
binding = "ASSETS"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "ishyura-db"
database_id = "e4e60ef4-0a65-4f90-8f9e-b67f444741f9"
migrations_dir = "migrations"

[vars]
ADMIN_SECRET = "ishyura2026"

