name = "ishyura"
main = "dist/server/server.js"
compatibility_date = "2024-09-01"

[assets]
directory = "dist/client"
binding = "ASSETS"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "ishyura-db"
database_id = "1fdb7bf0-71fb-40f7-b9e4-fa5334d11975"

[vars]
ADMIN_SECRET = "ishyura2026"

